### ISSUE TITLE
Fork conda-execute to conda-forge organization

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-execute-feedstock#17]
Would like to suggest that the `conda-execute` repository be brought over (forked) to `conda-forge`.

Basically the same story as `conda-build-all`. ( https://github.com/conda-forge/conda-build-all-feedstock/issues/30 ) We need to make some changes to `conda-execute` for `conda` 4.3 support. Given this is used by basically every service we have (re-rendering bot, pinning bot, updating the webpage, updating the docs, updating the feedstocks repo, etc.), it is pretty important that we update it to work with `conda` 4.3. However no one outside of Phil has merge permissions and he has been otherwise engaged for some time. I expect even he would want to see conda-forge progress on this issue. Given all of this, I think it is reasonable for `conda-execute` to be brought into conda-forge. Thoughts?

cc @conda-forge/core

**Comment by scopatz** [comment]
This seems reasonable to me!

**Comment by mwcraig** [comment]
👍

**Comment by pelson** [comment]
Honestly, I'm not sure how I feel about it. I'm 100% for it being moved out of my own userspace, but am also a little reluctant to force it upon conda-forge (FWIW I feel the same about conda-build-all). 
I'd like to solve the problem for more than just *us* in conda-forge, perhaps we should be talking about a conda-tools consortium/organisation outside of conda-forge...?

Besides, don't you guys think we've got enough repos yet 😜

**Comment by jakirkham** [comment]
FWIW the main motivation for proposing this was to finish up the `conda` 4.3 migration when you and others involved in these tools did not appear to be actively engaged. If you are actively engaged, then this just feels like work that is not needed, right? 😄

That said, definitely in favor of a conda-tools org. Would recommend adding all of conda-forge core as admins and potentially other stake holders on it.

**Comment by pelson** [comment]
> That said, definitely in favor of a conda-tools org.

Let's do that. The conda-execute has outlived being kept in my homespace, and conda-build-all will benefit from a wider collaboration base (outside of SciTools & conda-forge).

**Comment by jakirkham** [comment]
Have created the org, invited everyone from conda-forge core to conda-tools core, and gave everyone on core admin access.

**Comment by jakirkham** [comment]
With conda-build-all, now that there are two copies, which one do we migrate to conda-tools? The conda-forge copy is a little ahead of SciTools, but it has less history (e.g. issues and PRs). Or do we want to create a whole new repo and migrate things?

Would you be willing to migrate conda-execute or should we create a new repo and copy the history?

Also have added your email, @pelson, from conda-forge under billing for conda-tools. Hope that is ok. If not, we should figure out whose email should be there instead.

**Comment by pelson** [comment]
That works well. Let me catch up with my group at work to talk about conda-build-all, but I'm proposing we transfer the repository from SciTools/conda-build-all to conda-tools/conda-build-all to keep hold of its history.

I've already done precisely this with pelson/conda-execute.

**Comment by jakirkham** [comment]
I'm ok with that. How should we pull in the changes from the conda-forge copy?

**Comment by pelson** [comment]
The history is linear, right? We can just push (not forced) directly to master from conda-forge.

**Comment by jakirkham** [comment]
Yep should work.

**Comment by pelson** [comment]
Conda build all from SciTools has been transferred into conda-tools. Would you like to push from conda-forge @jakirkham?

**Comment by jakirkham** [comment]
Done. :smile:

**Comment by jakirkham** [comment]
Should add that I published the release that was already on conda-forge's conda-build-all on conda-tools' one.

**Comment by jakirkham** [comment]
Could you please try syncing Travis CI @pelson? I think it is confused about where conda-build-all lives now.

**Comment by pelson** [comment]
I've experienced similar blackholes when moving feedstocks in the past. A sync and a re-register seem to do the trick.

**Comment by jakirkham** [comment]
Yep, looks good now. Thanks.

**Comment by jakirkham** [comment]
Any thoughts on what we do with conda-forge's conda-build-all? Personally I'd like to not delete it, but we should indicate somehow that conda-tools is the home of conda-build-all. Have added a note in the description, but not sure if there is more we should do.

Edit: I guess we could migrate it to conda-tools and note it is an archive.

**Comment by mwcraig** [comment]
You could do one more commit, eliminating everything except the README,
which would indicate where the "real" repo is.

I don't see any reason not to delete it if you don't do some drastic like
this, because other wise it is going to get PRs in the future.

It seems like the conda-build-all and conda-execute repos
in conda-forge should be the repos that build those packages....

**Comment by jakirkham** [comment]
Eliminating everything, but the README is a good idea.

The main reason to not delete it is we lose much of the history from PRs (e.g. comments), which would be helpful should we need to understand why some decision was made or some other path not taken. In particular I'm thinking of the `noarch` PR or `conda` 4.3 support, which seem like things we might want/need to revisit down the road.

Agreed. Hence why I'm thinking about migrating that repo (mentioned in the edit).

Edit: Opened issue ( https://github.com/conda-tools/conda-build-all/issues/88 ) to discuss this further.

**Comment by jakirkham** [comment]
Deprecation of `conda-build-all` in PR ( https://github.com/conda-forge/conda-build-all/pull/10 ). Please let me know if the wording is ok or if it needs tweaks.

Edit: That PR has been merged. Though feel free to submit PRs for tweaks should they be needed.
